apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: service-b
  name: service-b-authorizationpolicy-role
rules:
#- apiGroups: [""] # "" indicates the core API group
#  resources: ["pods"]
#  verbs: ["get", "watch", "list"]
- apiGroups: ["security.istio.io"] # 
  resources: ["authorizationpolicies"]
  #resources: ["*"]
  verbs: ["get", "watch", "list", "delete", "deletecollection", "create", "patch"]